### ISSUE TITLE
Add working glyph

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/genepanel.iobio#10]
After selecting a disorder, it takes a few moments for results to populate. We need to have something indicating that the app is working while we wait for results

**Comment by adityaekawade** [comment]
I have also added an alert if the search term does not return any data.
![Screen Shot 2018-03-09 at 11.51.32 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a68ffc37453d30014ef4f0d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206454fa6b7191a379ee0c2e50415c4cbc30254d58eeb9cb74fce36f34985619e880640a20cf3443a9eed41fed04ba208a1d87b5ed824e94fa2137a5dad11b61435c52dcbd4f3fb29843c259f349e14b57a5163561e070306e0a.png)
