### ISSUE TITLE
Improve Phenolyzer page

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/genepanel.iobio#101]

**Comment by AlistairNWard** [comment]
![phenolyzer](https://user-images.githubusercontent.com/523111/39251111-80ac6d7c-4870-11e8-917e-6b43a2363801.png)

**Comment by AlistairNWard** [comment]
Another potential mockup:

![phenolyzer](https://user-images.githubusercontent.com/523111/39255945-b83d95d0-487b-11e8-8597-c1443a6e43b7.png)

**Comment by adityaekawade** [comment]
How about splitting the page to show both the genes and the charts?
![Screen Shot 2018-04-25 at 10.12.19 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a68ffc37453d30014ef4f0d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276456f66b7191a379ef0c2a53415e47bc30254d58eeb9cb74fce36f34985619e880640a20cf3443a9eed41fed04ba208a1d87b5ed824e94fa2137a5dad11b61435c52dcbd4f3fb2984cc259f349e54b52a61b346ae372336e0a.png)
