### ISSUE TITLE
Enable multiple search terms in Phenolyzer

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/genepanel.iobio#104]
Having searched on one term and generated a gene list, we should be able to then search on additional terms. As a first step, I included having a badge created for each search term, along with the number of associated genes. You could select one of these badges, and the user would be presented with the genes from that search.

The selected badge should be appropriately highlighted.

child #101
child #108

**Comment by adityaekawade** [comment]
When new terms are added they are selected by default. The user can delete those terms by clicking the "x" icon on the badge, and the gene list will be updated automatically. 

Can we add the highlighting option after the BOG?

**Comment by AlistairNWard** [comment]
Yes we can
