### ISSUE TITLE
Pie chart for set analysis of multiple search terms

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/genepanel.iobio#105]
If a user has selected multiple search terms, we could use a pie chart for defining sets. Consider searching on 4 different terms. The pie chart wedges could represent:

1. Genes present in all 4 search terms
2. Genes in 3 of 4 terms,
3...
n. Genes unique to a single term

This pie would be interactive, so the user could pick genes that are present in 3/4 and 4/4 etc. This could be discussed. It may be easier for selection purposes to show on a histogram instead.

child #101

**Comment by adityaekawade** [comment]
![Screen Shot 2018-04-30 at 9.42.00 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a68ffc37453d30014ef4f0d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276457f36b7191a371f116294f5f5f5edd3c4a4356bcbbd671f3e57862804e0ebcd8380b7dcf6f14faee824dba01ba21d94d86e7b48818d2f42f67b6d5db1063474f4dcbed5727a19e41c95df44ee04d57ad163567e6742431.png)

**Comment by AlistairNWard** [comment]
We can look at set analysis of gene lists at another point
