### ISSUE TITLE
Add GTR description

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/genepanel.iobio#110]
At the top of the GTR page, we should include a brief description of what the GTR resource is, with a link out to more information. For this description, we could use some or all of the description provided on the GTR page itself.

"The Genetic Testing Registry (GTR®) provides a central location for voluntary submission of genetic test information by providers. The scope includes the test's purpose, methodology, validity, evidence of the test's usefulness, and laboratory contacts and credentials. The overarching goal of the GTR is to advance the public health and research into the genetic basis of health and disease."

child #108

**Comment by adityaekawade** [comment]
I would prefer to have a collapsible box which opens when the "description" is clicked or something like that in future.

**Comment by AlistairNWard** [comment]
That's fine be me. I agree that taking up space with something that is only needed the first time or so is unnecessary. We should also figure out the landing page. We could for now include these description on the landing page, and they could be permanently viewable there.

**Comment by adityaekawade** [comment]
Yeah, I agree. And having it on the homepage would be great.
