### ISSUE TITLE
Phenolyzer term has no results

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/genepanel.iobio#112]
If there are no results, we still produce a badge for the search, but should probably highlight that there were no results. Maybe we have two sets of badges, one for those with results, and one for those without?

I think we still need to show all the terms that were searched on, even when there are no results.

child #101

**Comment by adityaekawade** [comment]
![Screen Shot 2018-04-27 at 4.00.34 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a68ffc37453d30014ef4f0d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276456f46b7191a37cf1122b4f5c5b5ecc3c4a4356bcbbd671f3e57862804e0ebcd8380b7dcf6f14faee824dba01ba21d94d86e7b48818d2f42f67b6d5db1063474f4dcbed5727a19141c95df44fe94b53a2173263e27e2431.png)
