### ISSUE TITLE
Search on gene doesn't seem to work

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/genepanel.iobio#113]
Search on Hypomagnesemia in GTR

1. In the gene search, type "C". No genes are filtered out. 

2. Now increase this to "CL" and the search kicks in properly

3. Also search on a couple of phenotype terms in Phenolyzer, go to the summary page and the search immediately filters out all terms.

**Comment by adityaekawade** [comment]
I have fixed it for the summary tab. 
For GTR and phenolyzer the search kicks in for the 2nd term. I am not sure right now why this is happening. I will need to spend some time on this. Is it a priority right now for BOG?

**Comment by AlistairNWard** [comment]
Nope, not a priority. I'll tag it in the BoG epic if I think we need it for that. In general, I issues that remain in the Backlog, are not things to jump on right now.
