### ISSUE TITLE
Clear all

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/genepanel.iobio#115]
Is there a sensible way of being able to clean out the whole app? If I've added terms in Phenolyzer and GTR and done a bunch of stuff, and now want to start again on a completely new search, can I clear out the whole app without just hitting refresh? Is there a recognized way of doing this?

**Comment by adityaekawade** [comment]
Yes, I can add a button to clear either GTR or Phenolyzer or both which will fire an event to unmount all the components which will basically clear the results. The user can then enter new search terms for new analysis.

**Comment by AlistairNWard** [comment]
Yeah, but let's just make sure we implement it in a standard, intuitive manner.

**Comment by adityaekawade** [comment]
I have added a button "New Analysis" in the navbar, clicking which refreshes everything without reloading.

**Comment by AlistairNWard** [comment]
Perfect. This is a good solution.
