### ISSUE TITLE
Make running / queued notification better

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/genepanel.iobio#120]
When you input a Phenolyzer query, the text "running" or "queued" appears. We should make this prettier.

child #101

**Comment by adityaekawade** [comment]
I have aligned this in the center and also added another loading gif.
![Screen Shot 2018-05-16 at 2.25.35 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a68ffc37453d30014ef4f0d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266455f56b7191a37af1102e4f5c5a5ecc3c4a4356bcbbd671f3e57862804e0ebcd8380b7dcf6f14faee824dba01ba21d94d86e7b48818d2f42f67b6d5db1063474f4dcbed5727a29b41c95df44de44d57a0143663e3702431.png)
