### ISSUE TITLE
GTR Go

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/genepanel.iobio#139]
If you open the GTR and click "Go" without entering a term, results are returned and a blank disorder is listed.

**Comment by adityaekawade** [comment]
I wanted to ask this, what data does this return and is this important?

**Comment by AlistairNWard** [comment]
I think the Go button should probably just be disabled until something is entered into the search bar. Hovering over the genes, it looks like the genes come from these disorders:

"Lamellar cataract, Cataract 3, multiple types, Cataract 21, multiple types"

Very odd!

![Screen Shot 2018-06-12 at 2.20.54 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5750332babe50b1300c53bf6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256455f16b7191a37af1102b4f5a5b5ecc3c4a4356bcbbd671f3e57862804e0ebcd8380b7dcf6f14faee824dba01ba21d94d86e7b48818d2f42f67b6d5db1063474f4dcbed5727a19e41c95df443e94f52a21b3e67e3712431.png)
