### ISSUE TITLE
Use another color than red for title bar, buttons

### ISSUE THREAD

**Issue by tonydisera** [iobio/genepanel.iobio#142]

**Comment by adityaekawade** [comment]
I like the color scheme of this design shared by Al. I am experimenting with these colors. 

![unnamed.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a68ffc37453d30014ef4f0d/125516c66e82c728ace21e0d46fd9a94228f86adcda5fd53b652fa912a5265296b51a2727581ba71bd177d075f0d4bac41590d46ffa88129f2a42062c80d55b98e30063e937f03a6aa8317b500bf22824681b1bd8848c5e83b37aa.png)
