### ISSUE TITLE
Vendor filtering

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/genepanel.iobio#151]
When we open the list of vendors, they should all be selected by default, and the user can deselect samples.

Probably should include a select/deselect all option.

**Comment by adityaekawade** [comment]
I have considered the following scenarios: 

Scenario 1:
1. I search for the term “Nager Syndrome”, it shows a list of 12 vendors and all are selected by default. 
2. I can deselect and reselect the vendors and the results are updated accordingly. 
3. “Select All” button show up when one or more vendors are deselected. Clicking it selects all the vendors from the list. 
4. I add another term “Treacher Collins Syndrome 1”, the list has now 23 vendors which are all selected by default. 

Scenario 2:
1. I search for the term “Nager Syndrome” and I deselect 2 vendors “CGC Genetics” and “CeGat GmvH”, so 10 out of 12 vendors are selected and the results are updated accordingly. 
2. Next, I search for the term “Treacher collins syndrome 1”, it shows 21 out of 23 vendors as selected. “CGC Genetics” and “CeGat GmvH” are deselected. 
3. I remove the term “Nager Syndrome” and it shows 19 out of 21 vendors selected. 
4. I click “select all” to select all 21 vendors. 

Scenario 3: 
1. I search for the terms “Nager Syndrome” and “Treacher collins syndrome 1” and selectively deselect all the vendors of Nager Syndrome and then proceed to remove the term “Treacher collins syndrome 1”. It gives a warning that at least one of the vendors should be kept selected. This is done to avoid showing a blank screen. As deselecting all the vendors would have zero panels selected. This is also the reason I have not added the deselect all option. 
The first vendor from the list is selected by default and the dropdown list is populated with the vendors' options. Select All button is also shown to the user.

**Comment by AlistairNWard** [comment]
It's good you've thought these through. This definitely makes sense to me. You may want to think about how that vendor card is then designed. If the only functionality in this card, is selecting/deselecting vendors, should it be in a drop down, or just always visible (when the card is selected).

Also, following on from these scenarios, would it make sense to provide a stronger visual indication when some of the vendors are filtered out? So you won't forget that you're not seeing the results from all vendors?

And, with regards to scenario 2, since I added a new disorder, and not all results for that disorder are shown (as a couple of vendors are already filtered out), would we want to provide a notification to the user to remind them of this? Probably not so intrusive that they have to click it away, but just to be sure that they are fully aware.

**Comment by adityaekawade** [comment]
Having a dropdown makes it easier to select the options. And I am using the `v-select` component of vuetify for this functionality which is very powerful.
 
We can show a notification when the user deselects at least one vendor. This will keep them aware that they have deselected and can then use the dropdown to reselect the options.

**Comment by AlistairNWard** [comment]
Wouldn't it make sense to have this card operate in the same way as the disorders card?

**Comment by adityaekawade** [comment]
Do you mean in terms of having checkboxes instead of drop-down or with respect to the functionality?

**Comment by AlistairNWard** [comment]
Yeah. I think where we have similar functionality in cards, we should have the same solution. Selecting vendors seems to be exactly the same functionality as selecting disorders, so we should probably have these cards behave the same way.
