### ISSUE TITLE
GTR info cards

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/genepanel.iobio#160]
Is there a better way of presenting the information in these cards? For example, this is the genes card:

<img width="452" alt="screen shot 2018-07-12 at 11 28 58 am" src="https://user-images.githubusercontent.com/523111/42643318-d75ca7e8-85c6-11e8-93d0-577519c13ff3.png">

All of the information is over at the left, leaving a lot of empty space in the card. Probably worth looking into different apps that show stuff in cards like this. Maybe we just need to center the information in the card, but maybe make the title stand out, maybe add some visualizations?

<img width="340" alt="screen shot 2018-07-12 at 11 32 51 am" src="https://user-images.githubusercontent.com/523111/42643611-8ddf545c-85c7-11e8-9d3d-b3c289760b96.png">

For the genes, as an example, maybe we include a shaded bar in the card as well as the numbers? Just a quick play:

![asset 1](https://user-images.githubusercontent.com/523111/42644827-828dd210-85ca-11e8-9263-7603e11f9164.png)

With the bar of the same type of the bar that appears in the table.

**Comment by adityaekawade** [comment]
This looks good! If you have used sketch can you share the css `box-shadow` value for this card?

**Comment by AlistairNWard** [comment]
Ha, sorry - I just threw it together in Illustrator. I don't have a license for sketch. Maybe I should get one though. If we are all using it, it would be good for us all to be able to share stuff.

**Comment by adityaekawade** [comment]
Is it possible to copy it from illustrator? 

Also, my license of sketch has expired. I tried to apply for the educational license, but they tell to apply with more proof as a copy curriculum. So we might have to get the standard license.

**Comment by AlistairNWard** [comment]
I can send you the illustrator ai file if that's useful. It definitely isn't put together properly though!

I'll see if Gabor will pay for you to get a license to Sketch.
