### ISSUE TITLE
Info card formatting

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/genepanel.iobio#161]
<img width="452" alt="screen shot 2018-07-12 at 2 54 02 pm" src="https://user-images.githubusercontent.com/523111/42653547-c3a2229c-85e3-11e8-898d-0dd480bd9fdb.png">

The "View and filter" button seems to divide up the text, so the word, e.g. present, seems to be disconnected from anything else. See also #160

**Comment by adityaekawade** [comment]
I have formatted the cards except the Modes of inheritance as we are still working on it.
