### ISSUE TITLE
Inheritance modes

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/genepanel.iobio#162]
I don't think the pie chart is really working. We have a limited number of available inheritance modes, so would it be better to just have a list of the available modes with check boxes? In keeping with the main list of genes table, we could include a bar next to each mode showing the number of genes that are contained in that inheritance mode.

By default, all modes are selected, but you can deselect modes you don't want. Also include select all, deselect all buttons.

Thoughts?
![Asset 6.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5750332babe50b1300c53bf6/125516c66e82c728ace21e0d46c987892696c3ffcda5fd53b652fa912a5265296b51a2727581ba71bd177d075f0d4bac41590d46ffa88129f2a42062c80d55b98e30063e937f03a6aa801fb500bf238a4b87b2bc8d4dc9e13437aa.png)

**Comment by AlistairNWard** [comment]
Although, maybe if we did something like that, it the number after each bar shows the number of genes with that inheritance mode, but not the total. Maybe we would want to see both numbers, or the total number somewhere?

**Comment by AlistairNWard** [comment]
In the non-selected view, we would just have a summary of the filters:
![Asset 2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5750332babe50b1300c53bf6/125516c66e82c728ace21e0d46c987892696c3fbcda5fd53b652fa912a5265296b51a2727581ba71bd177d075f0d4bac41590d46ffa88129f2a42062c80d55b98e30063e937f03a6aa8318b500bf238a4b87b5bb8848c8e93a37aa.png)

**Comment by adityaekawade** [comment]
I liked this. And it is much simpler to understand than Pie Chart. 

How should we handle this case? 
Dejerine-Sottas disease has only one associated disorder but it shows four modes of inheritance. Deselecting any of the modes will respectively deselect its associated disorder which in this case is only one and hence there will be no output.

**Comment by adityaekawade** [comment]
This is data (considering only: disorder name, mode of inheritance, gene count) we get when we search for disorder “Treacher Collins syndrome":  

Treacher Collins syndrome 1 - not provided - 509 
Treacher Collins syndrome 2 - 	Autosomal dominant inheritance - 504 
Mandibulofacial dysostosis - Autosomal recessive inheritance - 702 
Treacher Collins syndrome - Autosomal recessive inheritance, Autosomal dominant inheritance - 418 

Following are the analysis steps: 

Step 1: Split the data to get the unique modes of inheritance. 
Eg. Modes of Inheritance: Autosomal dominant inheritance, Autosomal dominant inheritance, not provided

Step 2: Add the gene count. 
(A). If I add the gene counts this will the following results: 

Not provided: 509 
Autosomal dominant inheritance: 504(Treacher Collins syndrome 2) + 418 (Treacher Collins syndrome) = 922
Autosomal recessive inheritance: 702 (Mandibulofacial dysostosis, Treacher Collins type, autosomal recessive) + 418 (Treacher Collins syndrome) = 1120


(B). Taking average where there are more than one modes are present 
Not provided: 509 
Autosomal dominant inheritance : 504  + (418/2) = 713 
Autosomal recessive inheritance: 702 + (418/2) = 911 


(C) Selecting the greater value 
Not provided: 509 
Autosomal dominant inheritance: 504 (As 504 > 418) 
Autosomal recessive inheritance: 702 

The total number of genes are 770 for this search. Duplicates are removed.

**Comment by AlistairNWard** [comment]
Ok. I think this is complicated, so here are some thoughts. How about we have a little bit of explanation about what is being shown and what deselecting will do.

![Asset 9.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5750332babe50b1300c53bf6/125516c66e82c728ace21e0d46c987892696c3f0cda5fd53b652fa912a5265296b51a2727581ba71bd177d075f0d4bac41590d46ffa88129f2a42062c80d55b98e30063e937f03a6aa8318b500bf238a4780b1bc8349c2eb3f37aa.png)

**Comment by AlistairNWard** [comment]
Ok, we could also think about this in another way. Deselecting modes of inheritance ultimately just deselects associated disorders, so why don't we combine them?

![Asset 10.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5750332babe50b1300c53bf6/125516c66e82c728ace21e0d46c987892696c3f8dfabf301b44fff9e2c4533317346f62a2980e771e6402e07095f1ca941585e16fefad823a4e22e6c981e5ab38532022d8c6853beb2901eb80bbb25884e8cb7bb834cc9e13c24f5c6.png)

The user can deselect any disorders that they want to get rid of, and/or they can remove modes of inheritance. If they deselect a mode, or combination of modes, that results in the removal of a disorder, they would see that happen in the card. This would maintain the connection between these parameters, as well as hopefully make it a little clearer what is going on. We could also add tooltips, so that if you hover over the disorder, you can see the associated modes of inheritance, or if you hover over a mode of inheritance, you see the associated disorders. Thoughts?

![Asset 11.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5750332babe50b1300c53bf6/125516c66e82c728ace21e0d46c987892696c3f8deabf301b44fff9e2c4533317346f62a2980e771e6402e07095f1ca941585e16fefad823a4e22e6c981e5ab38532022d8c6853beb2901dbf0bbb25884e8cb7b48a49c2eb3b27f5c6.png)

**Comment by adityaekawade** [comment]
I liked this! This will be much clear to the user about what is happening. The reason I had them as two separate cards was to maintain and keep a track of the state for the pie chart visualization. Also the reset filters button won't be required.

**Comment by adityaekawade** [comment]
What do the numbers on the right and the left of the bars in the Modes indicate? I assume one of them mean the number of times that mode is present in disorder. Example Autosomal Dominant is a mode of inheritance for two disorders?

**Comment by AlistairNWard** [comment]
I was just playing around! There are 4 disorders, so for the top inheritance mode, the '3' at the left is the number of disorders associated with autosomal recessive. The '1' at the right shows that one disorder isn't associated. It would make more sense to have the numbers actually in the bars. I just figured that it would be difficult to do when the small portion of the bar is very small.

![Asset 12.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5750332babe50b1300c53bf6/125516c66e82c728ace21e0d46c987892696c3f8ddabf301b44fff9e2c4533317346f62a2980e771e6402e07095f1ca941585e16fefad823a4e22e6c981e5ab38532022d8c6853beb2901dbf0bbb25884e8cb5bf8348c8e03d2df5c6.png)
