### ISSUE TITLE
Selected disorders

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/genepanel.iobio#164]
We need to think about this. First of all, it needs a better design. See #160, #162.

I also think this will be confusing. If someone searches on Treacher Collins Syndrome, they may be confused why there are, in fact, 4 disorders. Maybe the help text for the disorders box would explain this?

If we are going to use badges, it seems strange for them to appear to be inside a gray dropdown. Then, if I click the dropdown, I just see the same information again. What purpose does this serve? Maybe, we open this card and all the disorders are shown as badges, but get rid of the dropdown. There would be a fixed size area containing the badges that you could scroll down when there are a lot.

**Comment by adityaekawade** [comment]
I removed the gray background. 
Dropdown provides the option to deselect the items from the list. Checkbox would have been helpful here, but it is not reacting correctly. 
![Screen Shot 2018-07-12 at 8.44.59 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a68ffc37453d30014ef4f0d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77246455f16b7191a370f1162f4f5a565ecc3c4a4356bcbbd671f3e57862804e0ebcd8380b7dcf6f14faee824dba01ba21d94d86e7b48818d2f42f67b6d5db1063474f4dcbed5727a19041c95df54ae54855a41b356aef722431.png)

If I get rid of the dropdown: 
Then when we open this card, all disorders are shown as badges. User can click the cross and deselect the disorder that he does not want. And then there will be a reset button which would reselect all the disorders back again. 
Does this sound good?

**Comment by adityaekawade** [comment]
Another solution is having checkboxes for the list of options like #162. When we open this card all the checkboxes are selected and the user can check/ uncheck the boxes as required.

**Comment by adityaekawade** [comment]
I have tried this with the checkboxes instead of badges and dropdown. I think it looks much cleaner and easier to use.
![Screen Shot 2018-07-15 at 8.34.01 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a68ffc37453d30014ef4f0d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77246455f66b7191a370f1112f4f5f5e5ecc3c4a4356bcbbd671f3e57862804e0ebcd8380b7dcf6f14faee824dba01ba21d94d86e7b48818d2f42f67b6d5db1063474f4dcbed5727a19e41c95df54ae64d5da1103665e3712431.png)

**Comment by AlistairNWard** [comment]
I agree.

**Comment by adityaekawade** [comment]
Yes, we can add this bar. I had added it initially, but the right side was looking very crowded.
