### ISSUE TITLE
Gene list labels

### ISSUE THREAD

**Issue by tonydisera** [iobio/genepanel.iobio#168]
This is very minor, but I think that the red and yellow labels aren't working for the genes table.

<img width="311" alt="screen shot 2018-07-13 at 10 03 58 am" src="https://user-images.githubusercontent.com/8420103/42701579-3509fcf2-8684-11e8-901c-fd411099ea80.png">

The red usually denotes error or danger, so it seems to not align with the number of gene panels that a gene is in.  I would just use the blue color or the grey color.

The yellow badge is hard to see.  Also, what does yellow signify?  I usually think of yellow as a warning or a highlight.  But since we have this badge on every line, it doesn't seem to fit.  I would vote of a grey or blue background with white text.

**Comment by AlistairNWard** [comment]
Yes, I agree. If we wanted a distinct colour for the yellow badge, it would probably make sense to make the badges at the top showing the searched disorders should have the same colour showing the connection.
