### ISSUE TITLE
Make sure Phenolyzer description gives credit to authors, institution.  We might want to include the citation or a link to phenolyzer.

### ISSUE THREAD

**Issue by tonydisera** [iobio/genepanel.iobio#171]
Also, I noticed that 'Read more' takes me to a blank page and then I can't go back to the app in the browser window.
<img width="1068" alt="screen shot 2018-07-13 at 11 27 38 am" src="https://user-images.githubusercontent.com/8420103/42705285-0e2e6260-8690-11e8-9233-bc3e840a9e19.png">

**Comment by adityaekawade** [comment]
"Read more" show take to this link http://phenolyzer.wglab.org/. I tried it with my phone and my other laptop it was opening the correct page.

**Comment by AlistairNWard** [comment]
We should also cite their paper:

Yang, Hui, Peter N. Robinson, and Kai Wang. Phenolyzer: phenotype-based prioritization of candidate genes for human diseases. Nature Methods (2015).

**Comment by adityaekawade** [comment]
Where should I include the citation for this paper? 
Should I create a menu item "Software and resources" like gene?

**Comment by AlistairNWard** [comment]
Yes, see #182. I think we should be mirroring genes help menu where appropriate.
