### ISSUE TITLE
Remove reset filters

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/genepanel.iobio#176]
For example, look in the associated disorders card after searching on "Treacher Collins Syndrome". The reset filters button does nothing because we haven't deselected anything. Once I deselect a disorder, the "Select all disorders" button appears, and this has the same functionality as reset filters. Probably just have the select all disorders button present at all times, and remove the reset filters.

There is no deselect all button, since you are forced to have at least one selected disorder. But what if you have 100 disorders and you want to remove all but 1? Would we want a deselect all, and let them select the one that they want? Maybe not. Just a thought.

**Comment by adityaekawade** [comment]
The associated disorders and the mode of inheritance are interdependent as they are acting on the same data. 

For example: 
The search term is Treacher Collins and "Treacher Collins Syndrome 1" is one of the associated disorder. And "Not provided" is its mode of inheritance as it is not provided. 

So if I deselect "Treacher Collins Syndrome 1", keeping "Not provided" selected as an option in the mode of inheritance card contradicts it. 
Similarly deselecting the option "Not provided" from the "Mode of inheritance" was deleting the option "Treacher Collins Syndrome 1" from the disorders card. 

This is the reason I had added the reset filter. Clicking this button was resetting the previous options.

**Comment by AlistairNWard** [comment]
Yes, that makes sense, but is obviously very unclear to a user. Since this is an action on this card, the expectation would be that it operates only on this card. This actually strengthens my opinion on the comment I added to #162.
