### ISSUE TITLE
Phenolyzer typeahead incomplete?

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/genepanel.iobio#18]
If I search on "early infantile epileptic encephalopathy", the only available options include a number at the end. There is a result in the Phenolyzer (and the old gene.iobio) typeahead for this. Maybe you have clipped the list in this dropdown?

**Comment by adityaekawade** [comment]
I am including"early infantile epileptic encephalopathy" in the typeahead results now. But the list that I have used had options that include a number at the end for the term  "early infantile epileptic encephalopathy". And these do not give any result, so should I delete them?

**Comment by AlistairNWard** [comment]
This comment also applies to the GTR typeahead. There is no "early infantile epileptic encephalopathy" there either.

I don't think we should delete anything for now. We could come up with a plan to purge disorders from the GTR typeahead if they have no results, but we'd need to make sure that if GTR was updated so there were results, then we would need to make sure we could put it back.

I don't think we should delete anything from the Phenolyzer typeahead.

**Comment by adityaekawade** [comment]
![Screen Shot 2018-03-19 at 9.31.05 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a68ffc37453d30014ef4f0d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206455fa6b7191a371f1112a4f5f5a5edd3c4a4356bcbbd671f3e57862804e0ebcd8380b7dcf6f14faee824dba01ba21d94d86e7b48818d2f42f67b6d5db1063474f4dcbed5727a19e41c95df44ae54a56a11a3360ee772431.png)

It gets crowded when the results are more, we need to think about this in terms of design.

**Comment by AlistairNWard** [comment]
Was this last comment attached to this issue? Changing the typeahead changes the number of results?

**Comment by adityaekawade** [comment]
I haven't changed the typeahead, just added the term to its list. The screenshot I have attached shows that when the results are more the visualizations get very crowded. (I haven't pushed this change to nv-dev yet).

**Comment by AlistairNWard** [comment]
The visualization will certainly need to be refined to handle larger numbers of results. I just wasn't sure that this was relevant to this issue.

We should try and make sure we are pulling all relevant info to build the typeahead list. We need to be confident we have all disorders represented.

**Comment by adityaekawade** [comment]
Yes, I agree! I am moving this issue back to in progress.

**Comment by adityaekawade** [comment]
The results were there but I think the number of items in the typeahead dropdown were limited as a result some items were not shown. Please review if this works now.
