### ISSUE TITLE
Reduce separation between list elements

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/genepanel.iobio#187]
In the cards, e.g. vendors, there is a lot of space between each vendor. Since there can be a lot of vendors, we should probably reduce the spacing to make more visible.

**Comment by AlistairNWard** [comment]
This looks good on the vendors card, but the spacing doesn't seem to be consistent across all cards. Could these stylings be general properties that are applied consistently across all cards? Would make the code cleaner if they are all the same class with consistent styling.

**Comment by adityaekawade** [comment]
I have actually applied the same styling. The reason it is currently looking different on different cards because: 
The space of the card is split into columns. For example in the panels card, there are three columns at the moment, as a result, the text gets wrapped into the next line and increases the spacing between the two options. 
Some of the panel test names are long, which again gets wrapped into the next line.

**Comment by AlistairNWard** [comment]
Ok, both cards have text wrapping, so this isn't the problem. The vendors card is just a list, and the other a table, so it's the spacing associated with the rows that is causing the difference? Could we then just put the vendors in a table (probably without a title row), so they look the same?

![Asset 1.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5750332babe50b1300c53bf6/125516c66e82c728ace21e0d46c987892696c3f8cda5fd53b652fa912a5265296b51a2727581ba71bd177d075f0d4bac41590d46ffa88129f2a42062c80d55b98e30063e937f03a6aa8318b500bf23894c83b7be8f4bc3ec3f37aa.png)

**Comment by adityaekawade** [comment]
It is not actually a table, but it is arranged in that way. For example in the panels card, the test name takes 8 units, and Genes and conditions take 2 units each. Whereas the vendors' name takes the entire 12 units. 
I will make the vendors' list 8 units so they are consistent with the panels. I agree having a similar will be better!

**Comment by AlistairNWard** [comment]
Thanks Adit!

**Comment by adityaekawade** [comment]
Panels: 
![Screen Shot 2018-07-25 at 3.10.13 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a68ffc37453d30014ef4f0d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77246456f66b7191a37bf1132b4f5e5c5ecc3c4a4356bcbbd671f3e57862804e0ebcd8380b7dcf6f14faee824dba01ba21d94d86e7b48818d2f42f67b6d5db1063474f4dcbed5727a29941c95df549e44856a611356be6712431.png)

Vendors: 
![Screen Shot 2018-07-25 at 3.14.48 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a68ffc37453d30014ef4f0d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77246456f66b7191a37bf1132f4f5b575ecc3c4a4356bcbbd671f3e57862804e0ebcd8380b7dcf6f14faee824dba01ba21d94d86e7b48818d2f42f67b6d5db1063474f4dcbed5727a19e41c95df549e44856a713336bee722431.png)
