### ISSUE TITLE
Replace summary pie

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/genepanel.iobio#188]
I think it would make sense to get rid of the pie chart in the summary as well. Would it make sense to just have this as a list of check boxes like what you've done with the GTR cards? So we'd have the name (e.g. unique to GTR), followed by a bar showing how many genes are unique to GTR of the total etc.?

**Comment by AlistairNWard** [comment]
Sorry to keep iterating! But rather than have two cards, both of which are summarizing the genes, maybe we should just have one card on the summary page at the moment, combining the info from that is currently in the two?

**Comment by adityaekawade** [comment]
I think we would require information from both the cards but we can have it in a single card. One card is currently reflecting the selection of genes in the summary table and the other is summarizing the genes from GTR and phenolyzer.

**Comment by AlistairNWard** [comment]
Yes, we need the info from both. Just thought it would make more sense consolidated.  Again, if you prefer it the way it is - this is only a suggestion. My suggestions are often not good ones!
