### ISSUE TITLE
Icons for GTR and Phenolyzer

### ISSUE THREAD

**Issue by adityaekawade** [iobio/genepanel.iobio#189]

**Comment by adityaekawade** [comment]
Can we think of some icons for GTR, Phenolyzer, Summary, and the overview page which can be used on the left sidebar

@AlistairNWard  @tonydisera

**Comment by AlistairNWard** [comment]
Yes, this would be great. Not sure who would be best to come up with some. GTR just uses the letters on their site, so maybe we could make a nice icon that was just the letters? Phenolyzer has an icon:

![phenolyzer.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5750332babe50b1300c53bf6/125516c66e82c728ace21e0d46f89c9f2d8d8fb095ecad01e81fe086264c22703d46f9692584ba2dbb1b22035a0918ac135d5f44fdab8b28f7be3e24984019af80330b2b9b645bf9fa9015ad00b22a8a4a86b4bc8244c4ef3820ee8f9d02.png)

I'll try and make a version that we can use.

I'll see if I can come up with anything for the overview and summary.

**Comment by AlistairNWard** [comment]
Here is my Illustrator version of the Phenolzyer symbol in the blue from the panel app. I've also attached the ai file.

![Asset 12.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5750332babe50b1300c53bf6/125516c66e82c728ace21e0d46c987892696c3f8ddabf301b44fff9e2c4533317346f62a2980e771e6402e07095f1ca941585e16fefad823a4e22e6c981e5ab38532022d8c6853beb2901eb90bbb25884d85bfbf834bc9ee3e24f5c6.png)

**Comment by adityaekawade** [comment]
![Screen Shot 2018-07-25 at 5.20.49 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a68ffc37453d30014ef4f0d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77246456f66b7191a37df1102b4f5b565ecc3c4a4356bcbbd671f3e57862804e0ebcd8380b7dcf6f14faee824dba01ba21d94d86e7b48818d2f42f67b6d5db1063474f4dcbed5727a19e41c95df549e44b54a6163666ee742431.png)

GTR-> represent a list 

Phenolyzer-> Had to change this a little, because the original logo was not properly visible as an icon in the menu. I have kept it just a simple P in a box. Maybe we can write a small note  that this is just for representation purpose and not the original logo and we do not intend to alter their logo. 

Summary-> This icon represent merging data from different resources.

**Comment by AlistairNWard** [comment]
These work for now. We can come back to them if people have better ideas.
