### ISSUE TITLE
Size of bars

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/genepanel.iobio#202]
I'm unclear what the bar sizes and attached numbers refer to in the cards. For example, search on Treacher Collins Syndrome and go the associated disorders card. Apparently there are only 5 genes associated with Treacher Collins Syndrome 1 and 2, 7 associated with Mandibulofacial dysostosis, and 4 with Treacher Collins Syndrome. How do we have 770 genes in total then?

Add Nager Syndrome and Craniodiaphyseal dysplasia and again look at the associated disorders card. Deselect cranio... All the bars are rescaled. The bar associated with cranio... no longer fits on the card. Again, it's unclear what the numbers refer to, and to what the bars are scaled to.

**Comment by adityaekawade** [comment]
The numbers were going out of the svg width. The numbers are 504, 509, 702.. 
![Screen Shot 2018-07-23 at 8.39.31 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a68ffc37453d30014ef4f0d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77246456f06b7191a370f111224f5c5e5edd3c4a4356bcbbd671f3e57862804e0ebcd8380b7dcf6f14faee824dba01ba21d94d86e7b48818d2f42f67b6d5db1063474f4dcbed5727a19141c95df549e24853ac143465ee712431.png)

Cranio.. has 876 and when it was deselected the total gene count was 803, as a result the bar was going out of the max width.
![Screen Shot 2018-07-23 at 8.39.59 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a68ffc37453d30014ef4f0d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77246456f06b7191a370f111224f5a565edd3c4a4356bcbbd671f3e57862804e0ebcd8380b7dcf6f14faee824dba01ba21d94d86e7b48818d2f42f67b6d5db1063474f4dcbed5727a19041c95df549e24852a4133465ee742431.png)

**Comment by AlistairNWard** [comment]
Still need to think through the bars a little bit. I assume that the bars are scaled so that completely blue means that they have all the genes. In the example above, Craniodiaphyseal has 876 genes out of 1,249. So when all disorders are selected, there is an appreciable blue section (the bar represents 876 / 1,249 genes). If I deselect Craniodiaphyseal, then there are only 803 genes remaining, so the bar is now completely. But this is odd because a) the number of genes associated with this disorder is larger than the total number of genes, and b) this implies that all genes associated with Craniodiaphyseal are present, but they are not.

Maybe one solution is that the bars don't resize? The maximum width is fixed at the total number of possible genes (e.g. 1,249). Thoughts?

**Comment by adityaekawade** [comment]
Having the fixed width was a good solution. It looks more clear now. I will put this to review once I update the dev server.
