### ISSUE TITLE
Search genes bold

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/genepanel.iobio#206]
Is the text in a search box typically in bold?

**Comment by adityaekawade** [comment]
I did that as Tony had mentioned that some labels are gray and some are black. So I made some changes. I think this is looking too strong. Should I revert?

**Comment by AlistairNWard** [comment]
Totally up to you. I would probably just use the same font as in the disorder search box.

**Comment by adityaekawade** [comment]
Oh! I think you are referring to the placeholder text and I was referring to the label "Enter disorders". The search genes text has a class of label.

**Comment by AlistairNWard** [comment]
Sorry, should have attached an image!

![Screen Shot 2018-07-24 at 11.44.03 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5750332babe50b1300c53bf6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77246456f76b7191a379ee0c2f55415f4dbc30254d58eeb9cb74fce36f34985619e880640a20cf3443a9eed41fed04ba208a1d87b5ed824e94fa2137a5dad11b61435c52dcbd4f3fb29843c259f348e34951a3133067e074316e0a.png)
