### ISSUE TITLE
Summary page titles

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/genepanel.iobio#207]
The badges appear under the titles disorders and phenotypes, but these don't correlate with the table titles. Since the user needs to associate the values in the table with the badges at the top, these should be consistent, e.g. GTR disorders?

**Comment by adityaekawade** [comment]
I will change it to "GTR disorders" and "Phenotypes" in the column headers and badges at the top.

**Comment by AlistairNWard** [comment]
I would use "Phenolyzer" rather than "Phenotypes". We could start using multiple tools to generate lists based on phenotypes, but these results are specifically from Phenolyzer.

**Comment by adityaekawade** [comment]
I have changed it to "Phenolyzer"
