### ISSUE TITLE
Reduce size of genes table

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/genepanel.iobio#22]
Could we reduce the height of the lines in the genes table? This would mean reducing the size of the checkbox and bar as well. I think we want to see as many genes as possible in this list, so making the height of each row as small as we can, while retaining ease of reading the contents would be good.

**Comment by adityaekawade** [comment]
Reduced the height of each row, reduced the font as well as the height of the svg bar. Also, I hid the column which was also showing the number of panels.  the svg bar shows that number.
![Screen Shot 2018-03-19 at 4.53.21 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a68ffc37453d30014ef4f0d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206455fa6b7191a37cf117284f5d5e5ecc3c4a4356bcbbd671f3e57862804e0ebcd8380b7dcf6f14faee824dba01ba21d94d86e7b48818d2f42f67b6d5db1063474f4dcbed5727a19e41c95df44ae44d55a6133267ef7f2431.png)
