### ISSUE TITLE
Specific panels

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/genepanel.iobio#223]
We discussed and should consider moving the option to select/deselect specific/general panels etc. at the top of the page, probably under choosing the number of genes to select.

The reason for this would be so we can set the default to only select specific panels, and have it clear where you can add more general panels.

We would need to reconsider the positioning of settings wheel in this case.

**Comment by AlistairNWard** [comment]
Let's try setting the default to only having specific panels selected.

**Comment by adityaekawade** [comment]
I would prefer having "Moderate" and "Specific" selected. 
This is how it looks with only "Specific panels" selected:
![Screen Shot 2018-08-08 at 2.57.09 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a68ffc37453d30014ef4f0d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772b6454fb6b7191a37af1172c4f5f565ecc3c4a4356bcbbd671f3e57862804e0ebcd8380b7dcf6f14faee824dba01ba21d94d86e7b48818d2f42f67b6d5db1063474f4dcbed5727a19041c95df548e64b54ac1a3566ee712431.png)

**Comment by adityaekawade** [comment]
I have kept specific - less than 20 and moderate - less than 45 for now.
