### ISSUE TITLE
Associated genes

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/genepanel.iobio#224]
A lot of disorders come with associated genes. Matt included example of "Autoimmune thrombocytopenia" returns genes, but the gene FCGR2C is not present. Searching on the GTR website has this as an associated gene.

We should get these genes for searched disorders and include them in the list. They may not be on any panels, so we should force these to the top of the list (if the are multiple, they could be sorted on panel membership within that group). They may need some visual cue to explain them.

**Comment by adityaekawade** [comment]
Yes, I am still working on it. First I wanted to get the associated gene show up in the table and map it with the search term, which is working now. 
I noticed the duplication and wanted to discuss that. What you have mentioned above sounds good. When the associated gene exists in the panel we will show it only as the associated gene but we will also show the bar with the number of panels. When it doesn't exist in the panel (eg. Autoimmune thrombocytopenia) we will still show it at the top but it will have a bar that fills the maximum width. 
 Do you want the glyph to be shown next to the name of the gene to indicate that it is an associated gene? Also when an associated gene exists we can show a little box above the table that explains what the glyph means.
Also, can you find a case where there are multiple associated genes for a search term?

**Comment by AlistairNWard** [comment]
If the gene isn't present in any panels, I don't think we should include a fully filled bar. This would imply it is present on the most panels, rather than actually being on none. In this case, we could include concise text in lieu of the bar. e.g. not on any panels.

The glyph showing that it is an associated gene should be prominent, but exactly where in the table is up to you.

If you search for autism spectrum disorder on the GTR website, you get multiple associated genes (but this term isn't in there typeahead). Panel doesn't show any.

Also try "Common variable immunodeficiency 2". On the GTR website, this gives several associated genes, but panel doesn't give any.

Also - I knew you were still working on this and was stepping in with comments prematurely!! Couldn't help myself!

**Comment by adityaekawade** [comment]
These are the cases I was looking for.  I have currently added a basic icon to indicate the associated genes.
![Screen Shot 2018-08-07 at 12.21.49 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a68ffc37453d30014ef4f0d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772b6454f46b7191a379ed0c2950415b47bc21254d58eeb9cb74fce36f34985619e880640a20cf3443a9eed41fed04ba208a1d87b5ed824e94fa2137a5dad11b61435c52dcbd4f3fb29843c259f348e24b53a2103f63e074376e0a.png)

**Comment by AlistairNWard** [comment]
Looks good. We need to find a glyph that makes more sense, and also have somewhere that explains what these are.

**Comment by adityaekawade** [comment]
Can you think of another icon that would look better here? Or how about a circle that has A written inside it to indicate it is an associated gene. I had just googled "Associated icon" to find this glyph. 
And probably I can add a small alert box, which can be closed, above to table to explain the glyph

**Comment by adityaekawade** [comment]
Information shown with a closable alert: 
![Screen Shot 2018-08-08 at 11.48.01 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a68ffc37453d30014ef4f0d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772b6454fb6b7191a379ee0c2f59415f4fbc30254d58eeb9cb74fce36f34985619e880640a20cf3443a9eed41fed04ba208a1d87b5ed824e94fa2137a5dad11b61435c52dcbd4f3fb29842c259f348e24a50a4163461e375336e0a.png)

**Comment by AlistairNWard** [comment]
Yep, I like this. I'll work on the text
