### ISSUE TITLE
I keep hitting 'New analysis' and get annoyed because I don't realize this clears out all of the search terms

### ISSUE THREAD

**Issue by tonydisera** [iobio/genepanel.iobio#228]
<img width="154" alt="screen shot 2018-08-03 at 1 55 28 pm" src="https://user-images.githubusercontent.com/8420103/43662989-1366542c-9725-11e8-8a73-ddc2eb815b7d.png">

I still think this isn't the right place for this button.  But, I can concede that point.  Minimally, I think it would be better just to call it 'Clear' or 'Clear all' and then have a prompt to confirm that the user really wants to delete all of the terms.

**Comment by AlistairNWard** [comment]
I would change the text in the dialog. First of all, should the responses just be "Yes" and "No"? The text is specific to the tools we have now, but hopefully these will be expanded, so maybe the text should just read:

Clicking "Yes" will clear results from all pages and begin a new analysis.
