### ISSUE TITLE
Add genes filter

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/genepanel.iobio#23]
From the left panel, we can select the top N genes, where N is user definable. Include another filter to select genes that appear in at least N panels. The user may want to pull all genes that fall in at least 2 panels, for example

**Comment by adityaekawade** [comment]
The example is missing. I think the example would help me.

**Comment by AlistairNWard** [comment]
![filters](https://user-images.githubusercontent.com/523111/37654931-27e2f1b0-2c1a-11e8-9ab1-d77dae7f5430.png)

**Comment by adityaekawade** [comment]
I have considered the following cases: 
1. User selects genes presents in at least N panels - Genes present in N panels are selected 
2. User first selects top K genes and then selects genes present in N genes - 
  a. If the number of rows with N selection is less than the number of rows with K selection, 
       Number of rows with N selection is selected. 
        Example: User selects top 50 genes, and then selects genes present in at least 7 panels, 
       which results in 12 rows, then only 12 rows are selected. 
  b. If the number of rows with N selection is greater than the number of rows with K selection, 
       The number of rows with K selection is selected. 
        Example: User selects top 50 genes, and then selects genes present in at least 2 panels, 
       which results in 230 rows, then only 50 rows are selected. 

Let me know if this is how you wanted it.

**Comment by AlistairNWard** [comment]
Yes, this makes sense. But you make a good point. We don't want this to be confusing to the user, so we probably want to make it clear what are filters and what directs selection.

Since this is a filter, If I select genes present in at least 2 panels, we could remove all genes that are in only 1 panel from the gene list. Then we can choose to only select the top 50 genes. This is a selection and not a filter, and we would select a maximum of 50 genes, as there may be less than 50 genes left in the list. So there can be a distinction between a filter and a selection.

I think that we should leave this as you have implemented it, and discuss it with the larger group. So we can leave it in the review column for now.

**Comment by adityaekawade** [comment]
Yes, I was considering this option but I did not want to manipulate the original array (removing all genes that are in only 1 panel) and that is why I am doing operations in selection. I can implement this, but let's see how the discussion goes ahead!

**Comment by AlistairNWard** [comment]
Yes, this is the right attitude!
