### ISSUE TITLE
What would you think about making the search term bages more prominent (blue background, white text)?  I often forget that I have typed in a search term already.

### ISSUE THREAD

**Issue by tonydisera** [iobio/genepanel.iobio#257]
<img width="456" alt="screen shot 2018-09-03 at 2 25 49 pm" src="https://user-images.githubusercontent.com/8420103/45000836-654f3100-af85-11e8-94d1-8075598c1562.png">
<img width="749" alt="screen shot 2018-09-03 at 2 25 56 pm" src="https://user-images.githubusercontent.com/8420103/45000837-66805e00-af85-11e8-9855-ada7253468a1.png">

**Comment by adityaekawade** [comment]
The dark background looks much better.
![Screen Shot 2018-09-04 at 3.07.27 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a68ffc37453d30014ef4f0d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772a6454f76b7191a37bf1122c4f5d585ecc3c4a4356bcbbd671f3e57862804e0ebcd8380b7dcf6f14faee824dba01ba21d94d86e7b48818d2f42f67b6d5db1063474f4dcbed5727a19e41c95df54de14450a7163261ee722431.png)
![Screen Shot 2018-09-04 at 3.07.42 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a68ffc37453d30014ef4f0d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772a6454f76b7191a37bf1122c4f5b5d5ecc3c4a4356bcbbd671f3e57862804e0ebcd8380b7dcf6f14faee824dba01ba21d94d86e7b48818d2f42f67b6d5db1063474f4dcbed5727a19e41c95df54de14450a7163261ee732431.png)

**Comment by tonydisera** [comment]
Glad you like it!  I have it as a clin-specific style right now.  I'll try to remember to move it up to the general style.
