### ISSUE TITLE
Scaling on summary

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/genepanel.iobio#272]
The Gene card on the summary has three bars for the uniqueness of genes, but the scaling seems off.

1. Search for Dejerine-Sottas disease in GTR
2. Search for hammertoe in Phenolyzer

In the summary, there are 13 / 87 genes common to both sources, but the bar barely registers!! The unique genes are 37 / 87, or ~42%, but the bar seems more like 20%.

![Screen Shot 2018-09-05 at 5.52.04 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5750332babe50b1300c53bf6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772a6454f66b7191a37df117294f5f5b5ecc3c4a4356bcbbd671f3e57862804e0ebcd8380b7dcf6f14faee824dba01ba21d94d86e7b48818d2f42f67b6d5db1063474f4dcbed5727a19e41c95df54de04551a7153e6ae4712431.png)

**Comment by adityaekawade** [comment]
There was a small calculation error because of the padding. Fixed it.
