### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/genepanel.iobio#33]
When entering app, provide a more visual entry with call to action.

**Comment by AlistairNWard** [comment]
Include button to start on one of the tabs, e.g. launch on GTR

**Comment by AlistairNWard** [comment]
This landing page could itself be a tab

**Comment by adityaekawade** [comment]
I have created a basic mockup of the landing page.
![Screen Shot 2018-04-06 at 10.29.21 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a68ffc37453d30014ef4f0d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276454f56b7191a379ef0c2958415d4fbc30254d58eeb9cb74fce36f34985619e880640a20cf3443a9eed41fed04ba208a1d87b5ed824e94fa2137a5dad11b61435c52dcbd4f3fb29843c259f349e24f5ca7143765e773326e0a.png)

**Comment by AlistairNWard** [comment]
I'm leaving this open until we're happy it's complete. Currently, the Learn More buttons don't lead anywhere.

**Comment by AlistairNWard** [comment]
Actually, I will close this issue, and just create new smaller issues on specifics of the landing page.
