### ISSUE TITLE
Clear gene search

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/genepanel.iobio#349]
If you search for a gene, then want to clear the search, you have to manually delete the entered term. Would be better to just be able to clear the search

**Comment by adityaekawade** [comment]
Does this issue still persist on the dev version? I just tested and it clears the gene search when "clear all" is clicked.

**Comment by AlistairNWard** [comment]
It clears on clear all, but what if I only want to clear the gene search?

**Comment by adityaekawade** [comment]
I have added a dismiss icon "X" to clear the gene search.

**Comment by AlistairNWard** [comment]
Yes you have! Works for me.
