### ISSUE TITLE
Update tabs

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/genepanel.iobio#35]
Use material design (e.g. https://material.io/guidelines/components/tabs.html) for the tabs at the top of the page. For now, include the following tabs:

1. Home
2. GTR
3. Phenolyzer
4. Summary

The Home and Summary pages can just have a big coming soon message on them for now.

**Comment by adityaekawade** [comment]
I am using vuetify, so this is their link for the tabs with material design: https://vuetifyjs.com/en/components/tabs#introduction

There are several options, please let me know which one you want.

**Comment by adityaekawade** [comment]
I think the #Grow looks good for our needs: https://vuetifyjs.com/en/components/tabs#example-grow

**Comment by AlistairNWard** [comment]
Agree. Grow looks good to me.

**Comment by AlistairNWard** [comment]
This is looking way better!! Here are a couple of things I would do with the tabs:

1. Move home to the far left,
2. Increase the font size on the tab titles,
3. Reduce the height of the bar containing the tabs. In the vuetifyjs example, it looks like the height of the bar is about three times the height of the text (it looks like there are three bars, the title bar, the tab bar, and a solid bar in between, with the same colour as the tab bar - you could just remove this bar in between). See image below:

<img width="685" alt="screen shot 2018-03-27 at 9 58 53 pm" src="https://user-images.githubusercontent.com/523111/38004459-55d74ce2-320a-11e8-81cb-6d5d6052e86d.png">

4. When the mouse is hovering over the tabs, it should change to a selection pointer (see vuetify example)
5. Can we set the bar containing the tabs and the bar with the "genepanel.iobio" title to the same colour, e.g. #2c3e50, and the underline for the selected to colour #66d4ed
6.

**Comment by adityaekawade** [comment]
1. I have kept GTR as the first tab for development convenience. It defaults to the first tab, so if I keep Home as the first tab, I would have to switch tab every time I reload.  I will change the order when it is ready for production. 
2, 4. Regarding the styling, it is taking default styling from some other file of my project, I will rectify that. 
3.  I have actually removed those 3 bars, but for some reason, it is not showing as expected.

**Comment by adityaekawade** [comment]
Yeah, and it seems to be the latest feature on Vuetify. It was not showing up with the vuetify version that I had, so updated it as per their documentation and it still didn't show up. And then I checked the version from the cdn that was used in the codepen example because it was working there and updated with that version

**Comment by AlistairNWard** [comment]
One more comment on this. Can we keep the tabs in place when we scroll? At the moment, if you scroll down, you can no longer see the tabs and move to Phenolyzer, for example.

**Comment by AlistairNWard** [comment]
Can we set the bar containing the tabs and the bar with the "genepanel.iobio" title to the same colour, e.g. #2c3e50, and the underline for the selected to colour #66d4ed.

Also, there is a line between the top menu bar and the tab bar. Can we remove that.

**Comment by adityaekawade** [comment]
![Screen Shot 2018-04-09 at 2.54.32 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a68ffc37453d30014ef4f0d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276454fa6b7191a37af1172f4f5c5d5ecc3c4a4356bcbbd671f3e57862804e0ebcd8380b7dcf6f14faee824dba01ba21d94d86e7b48818d2f42f67b6d5db1063474f4dcbed5727a19e41c95df448e24d52a3173e66e1772431.png)

So, the entire bar for tabs (the box in red) and the title gets the color  #2c3e50, right? I have changed the color of the underline for selected (circled in yellow) to #66d4ed.

**Comment by AlistairNWard** [comment]
Yes, exactly. This would then look like the mockup. We could also change it back, or let people see it both ways and get a consensus.

**Comment by adityaekawade** [comment]
I tried various options for the navigation, let me know which looks best or if we need to try other color options as well: 

1. I added the color #2c3e50 for the entire tab bat and title, but the title is not clearly visible:
![Screen Shot 2018-04-10 at 11.01.58 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a68ffc37453d30014ef4f0d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276455f36b7191a379ee0c2b50415a46bc30254d58eeb9cb74fce36f34985619e880640a20cf3443a9eed41fed04ba208a1d87b5ed824e94fa2137a5dad11b61435c52dcbd4f3fb29843c259f349e2495da7163465e47e306e0a.png)


2. I added the #66d4ed for the title
![Screen Shot 2018-04-10 at 11.02.38 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a68ffc37453d30014ef4f0d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276455f36b7191a379ee0c2b53415c46bc30254d58eeb9cb74fce36f34985619e880640a20cf3443a9eed41fed04ba208a1d87b5ed824e94fa2137a5dad11b61435c52dcbd4f3fb2984dc259f349e2495da7163e62e2703f6e0a.png)


3. All the content in the navigation bar gets the #66d4ed color
![Screen Shot 2018-04-10 at 11.20.41 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a68ffc37453d30014ef4f0d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276455f36b7191a379ee0c2951415b4fbc30254d58eeb9cb74fce36f34985619e880640a20cf3443a9eed41fed04ba208a1d87b5ed824e94fa2137a5dad11b61435c52dcbd4f3fb29842c259f349e2495da7153563e472366e0a.png)

4.
![Screen Shot 2018-04-10 at 11.36.06 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a68ffc37453d30014ef4f0d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276455f36b7191a379ee0c2857415f48bc30254d58eeb9cb74fce36f34985619e880640a20cf3443a9eed41fed04ba208a1d87b5ed824e94fa2137a5dad11b61435c52dcbd4f3fb29842c259f349e2495da715336be57f336e0a.png)

I liked the 3rd option so far.

**Comment by AlistairNWard** [comment]
I don't think I put this down clearly. We don't want the title to have the colour #2c3e50, but the top bar containing the title. So basically that whole section has the same colour:

![asset 1](https://user-images.githubusercontent.com/523111/38645503-3e5cc070-3db2-11e8-8ff6-9e8d3b393042.png)

**Comment by adityaekawade** [comment]
Sorry, I realized after commenting and hence deleted the comment.

**Comment by AlistairNWard** [comment]
Haha. I saw that when my comment posted, I couldn't see your options any more! I wondered what had happened.

**Comment by adityaekawade** [comment]
I will shift the text colors between the navbar and tabs, but I think this is what you are looking for: 

![Screen Shot 2018-04-11 at 4.07.10 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a68ffc37453d30014ef4f0d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276455f26b7191a37cf1122c4f5e5f5ecc3c4a4356bcbbd671f3e57862804e0ebcd8380b7dcf6f14faee824dba01ba21d94d86e7b48818d2f42f67b6d5db1063474f4dcbed5727a19f41c95df448e54551a0153f67ee762431.png)

**Comment by adityaekawade** [comment]
How about this one?
![Screen Shot 2018-04-11 at 4.34.54 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a68ffc37453d30014ef4f0d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276455f26b7191a37cf1112f4f5a5b5ecc3c4a4356bcbbd671f3e57862804e0ebcd8380b7dcf6f14faee824dba01ba21d94d86e7b48818d2f42f67b6d5db1063474f4dcbed5727a19141c95df448e54553a5113661e5742431.png)

**Comment by adityaekawade** [comment]
![Screen Shot 2018-04-11 at 4.44.23 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a68ffc37453d30014ef4f0d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276455f26b7191a37cf1162f4f5d5c5ecc3c4a4356bcbbd671f3e57862804e0ebcd8380b7dcf6f14faee824dba01ba21d94d86e7b48818d2f42f67b6d5db1063474f4dcbed5727a19141c95df448e54553a31b3167e07f2431.png)

**Comment by AlistairNWard** [comment]
I think this looks good.
