### ISSUE TITLE
Make filter panel closable

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/genepanel.iobio#36]
Include the icon from gene.iobio at the top left to open/close the filter panel.

<img width="243" alt="screen shot 2018-03-27 at 12 54 11 pm" src="https://user-images.githubusercontent.com/523111/37982273-20e78eda-31be-11e8-9925-967a96ff3148.png">

**Comment by adityaekawade** [comment]
@AlistairNWard, I have made the filter panel closable, added all the filter option and made changes to the layout accordingly. Have a look at it! I have used the default styles currently and will be working on styling. It would be great to have your feedback.

**Comment by AlistairNWard** [comment]
This is looking way better already! Thanks Adit. If you finish up the other outstanding issues, I'll add some more issues today.
