### ISSUE TITLE
Export gene lists

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/genepanel.iobio#37]
Trial a solution to enable exporting genes from the top bar. Include an export option at the top right which opens a modal where the user can choose to copy to clipboard or export file for the genes from the current panel (GTR in this case), or from all panels (e.g. the final summary).

![export](https://user-images.githubusercontent.com/523111/37985248-436f24b0-31c6-11e8-9d1e-f962befd6644.png)

**Comment by adityaekawade** [comment]
What should the export functionality do? For example, should it allow the user to download the text file?

**Comment by AlistairNWard** [comment]
Yes, I wouldn't spend a huge amount of time on this. If it is difficult to do, you could just leave the export options greyed out. But, if it isn't too hard, just dumping a comma separated gene list to a text file would work for now.

**Comment by AlistairNWard** [comment]
As part of this, we can remove the copy to clipboard button in the Results card.

**Comment by AlistairNWard** [comment]
We either need to include options to copy/export genes from every tab at all times, or when using the Phenolyzer page, the top options change from GTR genes to Phenolyzer genes. Maybe we can always provide the option to export from all tabs, but it would be worth thinking about how to style it so that if we add more sources, this modal doesn't become too cluttered.

**Comment by adityaekawade** [comment]
I have added conditional rendering now, so when we are in GTR it will give options to copy/export GTR genes and when we are in Phenolyzer, option for Phenolyzer genes.
![Screen Shot 2018-03-30 at 10.52.56 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a68ffc37453d30014ef4f0d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206457f36b7191a379ef0c2e53415a48bc30254d58eeb9cb74fce36f34985619e880640a20cf3443a9eed41fed04ba208a1d87b5ed824e94fa2137a5dad11b61435c52dcbd4f3fb2984cc259f349e34957ac1b3f60e17e376e0a.png)

For Home and Summary, it shows options only to copy/export all genes.
![Screen Shot 2018-03-30 at 10.53.08 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a68ffc37453d30014ef4f0d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206457f36b7191a379ef0c2e52415f46bc30254d58eeb9cb74fce36f34985619e880640a20cf3443a9eed41fed04ba208a1d87b5ed824e94fa2137a5dad11b61435c52dcbd4f3fb2984cc259f349e34957ad123062e570326e0a.png)

This won't make the modal too cluttered.

**Comment by AlistairNWard** [comment]
Works for me.
