### ISSUE TITLE
Hover over gene highlighting

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/genepanel.iobio#45]
If a user hovers over a particular gene name, we should highlight where that gene lives in the charts. For example, if the gene is associated only with disorders listed as autosomal dominant, this wedge of the pie chart would be highlighted etc.

**Comment by adityaekawade** [comment]
The data received for genes does not directly have property for the mode of inheritance. It, however, shows the conditions and from there I can write a function to find the mode of inheritance for that condition. 

For example: 
For the term “Treacher Collins”, the top gene is TCOF1 and the conditions are all (Treacher Collins Syndrome, Treacher Collins Syndrome 1, Treacher Collins Syndrome 2, Mandibulofacial dysotosis, Nager Syndrome), which cover all the modes of inheritance which are shown in the pie chart. Now if the user hovers over ‘TCOF1’, all the wedges of the pie chart would be highlighted.

**Comment by AlistairNWard** [comment]
Yes, a gene itself certainly has no inheritance mode, just the disorders do. Some of these features will require some thought to make sure that they are useful.
