### ISSUE TITLE
Add disorder badges

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/genepanel.iobio#47]
We could potentially include badges for all disorders (like gene badges in gene.iobio). The user could deselect them and get some info about each disorder from the badge. This should be tested, especially with regard to how many disorders can come up with different search terms.

**Comment by AlistairNWard** [comment]
If the user hovers over a disorder badge, can we show more information about the disorder?

**Comment by adityaekawade** [comment]
I have added a tooltip that opens on the left when hovered over the associated disorder name. It shows the following information for the respective disorder: 
Mode of inheritance, OMIM, number of gene panels
![Screen Shot 2018-07-26 at 12.16.40 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a68ffc37453d30014ef4f0d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77246456f56b7191a379ed0c2a57415b4ebc21254d58eeb9cb74fce36f34985619e880640a20cf3443a9eed41fed04ba208a1d87b5ed824e94fa2137a5dad11b61435c52dcbd4f3fb2984cc259f348e34b57ad123765ee75356e0a.png)

**Comment by AlistairNWard** [comment]
Perfect!
