### ISSUE TITLE
Resize charts

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/genepanel.iobio#52]
1. The charts do not need to be in there own cards, they should just sit in the Results card.

2. We need the three charts to be sized so that they fit in the provided space, and don't appear squashed. 

Here is an example from hub.iobio, where we have 4 charts horizontally:

<img width="1348" alt="screen shot 2018-03-29 at 9 54 55 am" src="https://user-images.githubusercontent.com/523111/38092871-664cc4ca-3337-11e8-95fb-98c812f7dc87.png">

Note that the charts are not in their own cards and the font size is much smaller.

**Comment by adityaekawade** [comment]
Hi @AlistairNWard , Is it possible to share this repo with me? I would like to see how the charts are made responsive and if `viewBox` is used to scale the graphs. Also, I want to see how the histogram bins are stacked when the data is large.

**Comment by AlistairNWard** [comment]
I'll talk to Chase. This is actually a private company repo, so I can't just share it, but I should be able to get something for you.
