### ISSUE TITLE
Styling changes

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/genepanel.iobio#56]
I just put together a new mockup that we can work to for the next round of evaluation and feedback. We should aim to get this well styled for the next showcase.

![gene-panel](https://user-images.githubusercontent.com/523111/38101730-230bd5f8-334f-11e8-8587-717886a6785e.png)

Major points:

1. Export files and settings button (can leave this one out for now as we don't have any settings to change) at the top right

2. Scaled charts (#52)

3. Include number of genes selected, user selected top number of genes and gene search on one line to save space (#48)

4. Can trial having multiple columns of genes. This would need some thought, since putting two columns in this way would have an impact on scrolling.

**Comment by adityaekawade** [comment]
2. I have taken these charts out from their own card. This is how it is currently looking, but I am still working on it.
![Screen Shot 2018-03-29 at 11.09.46 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a68ffc37453d30014ef4f0d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206456fa6b7191a379ee0c2b58415b48bc30254d58eeb9cb74fce36f34985619e880640a20cf3443a9eed41fed04ba208a1d87b5ed824e94fa2137a5dad11b61435c52dcbd4f3fb29843c259f349e34e51a7163667e7713e6e0a.png)


3. I had just moved the number of genes selected text next to the card title. Do you like it?
![Screen Shot 2018-03-29 at 10.55.34 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a68ffc37453d30014ef4f0d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206456fa6b7191a379ef0c2e54415c4abc30254d58eeb9cb74fce36f34985619e880640a20cf3443a9eed41fed04ba208a1d87b5ed824e94fa2137a5dad11b61435c52dcbd4f3fb29842c259f349e34e51a7163160e574316e0a.png)


4. This needs to be studied. I haven't seen documentation about splitting into multiple columns with the vuetify tables. But can be figured out.

**Comment by AlistairNWard** [comment]
3. Yes, I think this looks good!

4. I would probably ignore this for the time being. It was just a thought that we can look into.
