### ISSUE TITLE
Bin data for charts

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/genepanel.iobio#62]
We should enable different binning in the two histograms. In the case that there are lots of results (e.g. cardiomyopathy), we should have bigger bins. Can we dynamically choose bin width based on incoming data?

**Comment by adityaekawade** [comment]
I am able to dynamically choose the different number of bins based on incoming data. But it is interfering with the brush functionality. Need to look into this properly.

**Comment by adityaekawade** [comment]
I am now able to display the histograms without clutter even for large data. The following screenshot is for cardiomyopathy.
![Screen Shot 2018-04-02 at 9.54.34 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a68ffc37453d30014ef4f0d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276454f16b7191a371f1172f4f5c5b5ecc3c4a4356bcbbd671f3e57862804e0ebcd8380b7dcf6f14faee824dba01ba21d94d86e7b48818d2f42f67b6d5db1063474f4dcbed5727a19e41c95df449e64f52ac133e64ee7f2431.png)

**Comment by AlistairNWard** [comment]
This is fantastic. Any way of making the y axis labels a bit more uniform for the Gene membership chart?

**Comment by adityaekawade** [comment]
The Y axis is log formatted and the labels are formatted accordingly. As a result, it doesn't take the regular ticks() method of d3 which helps to evenly space the ticks as per the argument passed.

**Comment by adityaekawade** [comment]
I have got the number on every other tick mark.
![Screen Shot 2018-04-03 at 12.08.33 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a68ffc37453d30014ef4f0d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276454f06b7191a379ed0c2b59415c4dbc21254d58eeb9cb74fce36f34985619e880640a20cf3443a9eed41fed04ba208a1d87b5ed824e94fa2137a5dad11b61435c52dcbd4f3fb2984cc259f349e34a5da413366aef703f6e0a.png)

**Comment by AlistairNWard** [comment]
Perfect.
