### ISSUE TITLE
Remove thick gray lines from chart selection

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/genepanel.iobio#75]
The gene membership chart is interactive, but we should remove the thick gray lines and arrows at the sides of the selection box.

Also, selecting outside of the gray box should make the selection box disappear and all genes would be selected (see behaviour of charts in hub)

**Comment by adityaekawade** [comment]
I have a doubt in this. When the chart loads, it selects a portion of the number of genes (50). The user can then move the brush to make the custom selection. So when the selection box is disappeared, shouldn't it deselect all the genes?

**Comment by adityaekawade** [comment]
I had missed a point in the above comment. I got it now.

With the selection box: 
![Screen Shot 2018-04-20 at 8.51.35 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a68ffc37453d30014ef4f0d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276456f36b7191a370f1172a4f5c5a5ecc3c4a4356bcbbd671f3e57862804e0ebcd8380b7dcf6f14faee824dba01ba21d94d86e7b48818d2f42f67b6d5db1063474f4dcbed5727a19141c95df44fe34a5ca5143767e4722431.png)

When selection box is made to disappear by clicking outside the gray box:
![Screen Shot 2018-04-20 at 8.51.47 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a68ffc37453d30014ef4f0d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276456f36b7191a370f1172a4f5b585ecc3c4a4356bcbbd671f3e57862804e0ebcd8380b7dcf6f14faee824dba01ba21d94d86e7b48818d2f42f67b6d5db1063474f4dcbed5727a19e41c95df44fe34a5ca617366be4772431.png)

**Comment by AlistairNWard** [comment]
That's a fair point. This behaviour mirrors how we have the charts set up in hub. Basically, if you include a selection box, you have the genes inside that box selected, if you have no selection box, you have everything selected. I agree with you that it might be more logical that deselecting the box would deselect all genes, but I think a users actions are more likely wanting to select everything.
