### ISSUE TITLE
Opening filter panel squashes charts

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/genepanel.iobio#81]
When the side panel opens, the charts are all resized, but the aspect ratios should be preserved. The pie chart needs to remain circular.

**Comment by adityaekawade** [comment]
I have made some changes, please let me know if this looks fine? 

With Filter panel closed:
![Screen Shot 2018-04-18 at 2.52.49 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a68ffc37453d30014ef4f0d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276455fb6b7191a37af117294f5b565ecc3c4a4356bcbbd671f3e57862804e0ebcd8380b7dcf6f14faee824dba01ba21d94d86e7b48818d2f42f67b6d5db1063474f4dcbed5727a19141c95df44fe14551ad123167e2702431.png)

With Filter panel opened:
![Screen Shot 2018-04-18 at 2.53.05 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a68ffc37453d30014ef4f0d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276455fb6b7191a37af117284f5f5a5ecc3c4a4356bcbbd671f3e57862804e0ebcd8380b7dcf6f14faee824dba01ba21d94d86e7b48818d2f42f67b6d5db1063474f4dcbed5727a29b41c95df44fe14551ad103361e5732431.png)

The visualizations are resized but the pie chart remains circular. You can check the pie chart of the GTR. This becomes important with respect to #83.

**Comment by AlistairNWard** [comment]
Yep, that looks good to me. When the charts resize, is the text in the charts getting squashed rather than reducing the font size?

**Comment by adityaekawade** [comment]
Yeah, the text is getting squashed. I am checking how the text in the svg is resized.
