### ISSUE TITLE
Clean up filter panel

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/genepanel.iobio#83]
Take a look at the filters in the vue version of gene.iobio.

<img width="526" alt="screen shot 2018-04-17 at 9 33 46 am" src="https://user-images.githubusercontent.com/523111/38872937-82ef817c-4222-11e8-97c7-ccbffdab83d1.png">

We could think about removing the side panel for the filters. This would remove the issue of resizing charts (#81). We could add a settings button in the Results card that similarly opens a modal and organizes the filter options above.

This is just a suggestion. We could also keep the side panel as is, but just try and make it look cleaner and more organized.

**Comment by adityaekawade** [comment]
I have cleaned up much of the filter panel, by removing much of text and adding some visual icons and following the input style from the vue Gene.iobio. Let me know your feedback. You can check it on the dev server.

**Comment by AlistairNWard** [comment]
Holy crap, this looks so much better! Looks really clean and nice; I like it a lot. Here's a question though. Is it usual behaviour to have a card as a navigation panel from the left? I think this probably needs to be a proper navigation drawer, and consequently not a card. I think we had it as a card when it was a permanent part of the page, but now it's a pull out, this probably isn't correct. Probably worth checking this with Tony.

But - this really is starting to come together!!!

**Comment by adityaekawade** [comment]
Yeah. This is looking much better! Thank you! 
I can remove the card from the filter panel.

**Comment by adityaekawade** [comment]
I have removed the card from the filter panel. This material design for the navigation drawer is based on YouTube and Google contact: 

On large device:
![Screen Shot 2018-04-23 at 11.32.14 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a68ffc37453d30014ef4f0d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276456f06b7191a379ee0c2853415e4abc30254d58eeb9cb74fce36f34985619e880640a20cf3443a9eed41fed04ba208a1d87b5ed824e94fa2137a5dad11b61435c52dcbd4f3fb29843c259f349e54855a01b3067e472346e0a.png)

On small screen:
![Screen Shot 2018-04-23 at 11.32.36 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a68ffc37453d30014ef4f0d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276456f06b7191a379ee0c2853415c48bc30254d58eeb9cb74fce36f34985619e880640a20cf3443a9eed41fed04ba208a1d87b5ed824e94fa2137a5dad11b61435c52dcbd4f3fb29843c259f349e54855a01b3e62e675326e0a.png)

**Comment by AlistairNWard** [comment]
Yep, like it. We can update functionality as necessary in other issues.
