### ISSUE TITLE
Add links to gene resources

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/genepanel.iobio#91]
When we hover over a gene name in the GTR table, we get a tooltip describing the disorders. We should be able to provide links to different gene resources as well. You can ask Matt for some good resources that we could link to (e.g. GeneReviews, OMIM). 

How would we want to provide links? Should we open a modal? Should we be able to click a gene to open a new row in the table where we have this information (like your ClinGen suggestion)?

These resources should be available from all tabs. When in GTR, there would be additional GTR information, e.g. disorders etc., but external resources should be available from all tabs.

For genes with a ClinGen entry, we probably would want to maintain a separate view. So maybe from each gene you can open focused modals, or content opening in a new table row? We should design this with the idea that there are multiple views. I'll leave it to you to come up with solutions to trial.

**Comment by adityaekawade** [comment]
![Screen Shot 2018-05-16 at 4.00.39 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a68ffc37453d30014ef4f0d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266455f56b7191a37cf1122b4f5c565ecc3c4a4356bcbbd671f3e57862804e0ebcd8380b7dcf6f14faee824dba01ba21d94d86e7b48818d2f42f67b6d5db1063474f4dcbed5727a19041c95df44de44d5da4153660ef742431.png)
