### ISSUE TITLE
What are the "Unique Genes" in the summary pie chart

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/genepanel.iobio#92]
The pie chart in the summary tab has "unique to GTR", "unique to Phenolyzer", both, and then "Unique genes". It seems that the "Unique genes" in the union of the unique to GTR and unique to Phenolyzer sets. Unless I'm misunderstanding, this should be removed.

**Comment by adityaekawade** [comment]
I agree, "unique genes" is not required.
