### ISSUE TITLE
Add citations

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/genepanel.iobio#93]
Again, take a look at the vue version of gene.iobio. There is a Help option at the top right that includes version info, disclaimers, and citations/references for software used. We should add the same to this, specifically the disclaimer, and acknowledgements, in particular for Phenolyzer and GTR.

Material design has suggestions for help items:

https://material.io/guidelines/patterns/help-feedback.html#help-feedback-placement

<img width="763" alt="screen shot 2018-04-17 at 10 32 24 am" src="https://user-images.githubusercontent.com/523111/38876558-afcde41a-422a-11e8-95fa-45fd022dab10.png">

We could use the same icon in the top right.

**Comment by adityaekawade** [comment]
Do you want to have only the icon or the text "Help" or both the text and the icon?

**Comment by AlistairNWard** [comment]
I think the icon is generally understood, so would probably go with that alone. Maybe talking to Tony and pick something that we do in both apps.

**Comment by adityaekawade** [comment]
With text: 
![Screen Shot 2018-04-17 at 3.41.55 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a68ffc37453d30014ef4f0d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276455f46b7191a37bf1162a4f5a5a5ecc3c4a4356bcbbd671f3e57862804e0ebcd8380b7dcf6f14faee824dba01ba21d94d86e7b48818d2f42f67b6d5db1063474f4dcbed5727a19e41c95df44fe14d54a21a3164e27e2431.png)

With icon:
![Screen Shot 2018-04-17 at 3.41.45 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a68ffc37453d30014ef4f0d/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276455f46b7191a37bf1162a4f5b5a5ecc3c4a4356bcbbd671f3e57862804e0ebcd8380b7dcf6f14faee824dba01ba21d94d86e7b48818d2f42f67b6d5db1063474f4dcbed5727a19041c95df44fe14d54a3113e63ee722431.png)

Tony thinks the help text is better in Gene.iobio and question mark is good for context sensitive help.

**Comment by adityaekawade** [comment]
I have currently used the icon and created placed holders for disclaimer and other items and added some random text or data from gene.

**Comment by AlistairNWard** [comment]
Yeah, I like that

**Comment by AlistairNWard** [comment]
This is good, but I'm going to leave it in progress until we have the text sorted.
