### ISSUE TITLE
Deselecting genes in summary table should updated pie

### ISSUE THREAD

**Issue by AlistairNWard** [iobio/genepanel.iobio#96]
In the Summary tab, if I deselect genes from the list, should the summary pie chart update? I deselected all shared genes, and the pie chart still shows the view of all samples.

You could argue that not updating the chart allows you to go back and select the shared genes and that would update the title. Are there standard ways that this should work?

**Comment by adityaekawade** [comment]
Yeah, I had thought about this. And my assumption was that the pie chart is created based on the genes that are selected from the GTR and Phenolyzer. 
When I select or deselect the genes from the summary, it updates the genes that can be copied or exported but no the chart as it is based on the genes that passed to the summary tab and not the selection from the summary. 
But I agree this is a good point and I can make the pie chart to update based the selection if you prefer it that way!

**Comment by AlistairNWard** [comment]
I agree. Let's leave it as is.
